# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: cd proxy && go build -v

    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
          username: 'root'
          server: '43.129.207.231' #测试服务器地址
          ssh_private_key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAwbRWQz0GcSy4jLvCtn99QU2O25u24ytqbC3ozpjEz1F5QnFqx1Po
E76BZxKb6DK7laKtyL4Xee4zaEgNiKbZjnOLXZWWK5n2PPgP0mAjdXXIIoj/0wRULOAVb7
ydvs9LSQ4eaNLCb3yycZbqdxSCD/U3y7vEWeaBJdFwRuJ/vLQfbovKdRbM/heEmhQGgLCA
A96X07asvff/Mzp4yZ7Plh7bPuJQZF6clwsiCc4qrlZDxQzA6lTahZi55BY2S/mYxTDJs9
ivWaGgkIt4Jm2mTZw/NvA5YGyPydW4agAua+6ZoJSIkAq8u3bL8McOzcw+7qAsam82MA+Q
IRALEPovsTh3hPAun+HoBfxfv4TlRMgv0jy438Jt4PvTybDi/YUUmuhzGyLJJi40FW0LnY
5c3YeJFqH/axJu3N94U4Zu334qQyf8wFb22ES7Ix+inNNGoa/UuDTUhf4Vk2zcAWzZCQC4
jgnW8AZYO9R8fg4lfkdTiGXMrB3GeR+5G1W8d35FAAAFkKvKZPyrymT8AAAAB3NzaC1yc2
EAAAGBAMG0VkM9BnEsuIy7wrZ/fUFNjtubtuMramwt6M6YxM9ReUJxasdT6BO+gWcSm+gy
u5Wirci+F3nuM2hIDYim2Y5zi12VliuZ9jz4D9JgI3V1yCKI/9MEVCzgFW+8nb7PS0kOHm
jSwm98snGW6ncUgg/1N8u7xFnmgSXRcEbif7y0H26LynUWzP4XhJoUBoCwgAPel9O2rL33
/zM6eMmez5Ye2z7iUGRenJcLIgnOKq5WQ8UMwOpU2oWYueQWNkv5mMUwybPYr1mhoJCLeC
Ztpk2cPzbwOWBsj8nVuGoALmvumaCUiJAKvLt2y/DHDs3MPu6gLGpvNjAPkCEQCxD6L7E4
d4TwLp/h6AX8X7+E5UTIL9I8uN/CbeD708mw4v2FFJrocxsiySYuNBVtC52OXN2HiRah/2
sSbtzfeFOGbt9+KkMn/MBW9thEuyMfopzTRqGv1Lg01IX+FZNs3AFs2QkAuI4J1vAGWDvU
fH4OJX5HU4hlzKwdxnkfuRtVvHd+RQAAAAMBAAEAAAGAWYzfnHIn+kZsg1OCbxB9faU3eD
uCz38Q0jZfPLPPuPC3mIoKjWAzGH2oIVivDyf1JPZyVS3ceJgw1/MHnrdUONEeCwPOyxWA
iys7VUzw16q9/YlMi+eiaqSmBGQ0oTQAYCPQ1zEohpYlgPH+L1Mh1fLN+rgxzEYOSseKmp
q35yt2pIqn7H3AA3An83tyjigK5r8Pfecj8Scnqi1MDhoHaiWVwnqqI9zBk+qnr9TKUpK6
/ewpe6wC4mR6/AFw1KrssAxr2MMla2bGKDnyp0k7tbOoHWnGKKfzeJUlRuh5dE7Iu94Y7e
P5iROn4dMryNRKZnJbA7YuSBaKfctnkTB62W46WONjl1FW1n3ms4CbbghQ0OtRBBXUNj7K
rJxkDWQ6t5uTTJ12a6oDxrtaKacw4um+lhJQZ/aQfxpv/2uIXl1z1Sprud3UuJokR+OeU8
xsLyvorxCiDwhxSc1jX/9qQMkAYp0mUmZvwa//rXhgrFx16RQ2/yH1b74xQDL27av5AAAA
wQDPLs87CHzkWK4Q//cXnzdoJcqgv7SyyeZXxIYGSowxvQRTPbXlAUOvwaavsXXlc9PyAs
CzYLxqaMELypQ+z2qAjKK55M/P0LlWoMKA1X8fPyRqgfFMmT6qhcGj+tnpU+2vsnB3SO+X
dHbnw8aul2D59wLZkLZCS2fbRKfJWUddrTm3VbWww7bUCEPl5VSSIU6LoaBvj78crUCZwB
lAMyIDCSQiNt1GKuQkQ5dS2RjufFbMDBE/aMm5mS6k+1JfiZ8AAADBAP15G3a8R8mw2lH8
BEGs/CwOB+CdFUmV7vzL3oFELxHS8pu6gKQ+ECh5u8+YqBRNSMf6gU4bRIXtB8WTWb5qTD
ZVpo1f0b+Zu1omRKTljslM2yyqwoOlbxFtHw4GVvPIWs3zbkhu2sOmEiuu1B/qPo5GHpn+
jIuCB8uN+nV3u72h+FxUFx4vW5CIYAwy9NYUEnagifnOv4a4So+CoTVJcd0ydSSM0FLrX5
ttM14OpIL6gRWkaGbsRugt7FA8AZBV5wAAAMEAw6KxdNW3HgHUOmcBpa/tJNKFzmRHrKmK
gcQYGKUDFHug+wbFsdzeNsdRE3v8qu20tmpxUPDQz6BbM3ATHGJUPxsXV1Too+CzqQqzp5
B1gM6ZzZoxTtLbl9ETpE2Uwnj6QQhTljcxPnL62oZKgqYKUULbSbb6zhDLvJRveIiKumPo
VgC41Q7Cppkuk+0D1HqyOEYYlHHeLiVLPcmjipkZ39FuL6ojQs8CfpL5c5zl6XZXEvAqvE
EXUepFiDJB8+zzAAAAE3Jvb3RAVk0tMC0xNi1jZW50b3MBAgMEBQYH
-----END OPENSSH PRIVATE KEY-----
          local_path: 'proxy/proxy'
          remote_path: ${{ secrets.TARGET }} #测试服务器部署路径
